[package]
name = "tura"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking"] }
rodio = "0.21.1"
